"use client";

import { useState } from "react";
import type { TravelReport } from "@/types/travel";
import SafetyBanner from "./SafetyBanner";
import Attractions from "./Attractions";
import Cuisine from "./Cuisine";
import PracticalInfo from "./PracticalInfo";

interface Props {
  report: TravelReport;
  destination: string;
  onReset: () => void;
}

export default function TravelReport({ report, destination, onReset }: Props) {
  const [safetyAcknowledged, setSafetyAcknowledged] = useState(
    report.safety.level !== "RED"
  );

  const blocked = report.safety.level === "RED" && !safetyAcknowledged;

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            Travel Guide: {destination}
          </h1>
          <p className="text-sm text-gray-500 mt-0.5">
            Your personalized travel recommendations
          </p>
        </div>
        <button
          onClick={onReset}
          className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          ← Plan Another Trip
        </button>
      </div>

      {/* Safety — always shown first */}
      <SafetyBanner
        safety={report.safety}
        acknowledged={safetyAcknowledged}
        onAcknowledge={() => setSafetyAcknowledged(true)}
      />

      {/* Rest of report — gated behind RED acknowledgment */}
      {!blocked && (
        <>
          <Attractions attractions={report.attractions} />
          <hr className="border-gray-200" />
          <Cuisine cuisine={report.cuisine} />
          <hr className="border-gray-200" />
          <PracticalInfo practical={report.practical} />

          <div className="rounded-lg bg-gray-50 border border-gray-200 p-4 text-xs text-gray-400 text-center">
            Report generated by Claude AI · Always verify safety information with official government travel advisories before travelling.
          </div>
        </>
      )}
    </div>
  );
}
